/**
 * Interactive configuration wizard for Pulse CLI.
 *
 * `pulse configure` — guides the user through setting up their provider
 * and API key, writing the configuration to ~/.pulse/.env.
 *
 * `pulse login` — alias for `pulse configure` with a focus on API key entry.
 *
 * @module commands/configure
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');
const os = require('os');
const chalk = require('chalk');
const { knownProviders, providerDefaults } = require('../lib/config');

// ── Config directory ───────────────────────────────────────────────────

function pulseDir() {
  return path.join(os.homedir(), '.pulse');
}

function envPath() {
  return path.join(pulseDir(), '.env');
}

// ── Helpers ────────────────────────────────────────────────────────────

function askQuestion(rl, query) {
  return new Promise((resolve) => {
    rl.question(query, (answer) => resolve(answer));
  });
}

async function selectProvider(rl) {
  const providers = knownProviders();
  console.log(chalk.bold('\n  ── Select a Provider ──\n'));
  providers.forEach((p, i) => {
    console.log(`  ${chalk.cyan(String(i + 1))}. ${chalk.bold(p)}`);
  });
  console.log();

  while (true) {
    const answer = await askQuestion(rl, `  ${chalk.cyan('Provider')} [1-${providers.length}]: `);
    const idx = parseInt(answer.trim(), 10) - 1;
    if (idx >= 0 && idx < providers.length) {
      return providers[idx];
    }
    console.log(chalk.red(`  Please enter a number between 1 and ${providers.length}.\n`));
  }
}

async function enterApiKey(rl, provider) {
  const defaults = providerDefaults(provider);
  const needsKey = provider !== 'ollama';

  if (!needsKey) {
    console.log(chalk.dim('  Ollama runs locally — no API key required.\n'));
    return '';
  }

  console.log(chalk.dim(`  Your API key for ${chalk.bold(provider)} will be stored in ~/.pulse/.env`));
  console.log(chalk.dim('  It is only used to authenticate with the provider.\n'));

  const key = await askQuestion(rl, `  ${chalk.cyan('API Key')}: `);
  return key.trim();
}

async function configureModel(rl, provider) {
  const defaults = providerDefaults(provider);
  if (!defaults) return '';

  const answer = await askQuestion(
    rl,
    `  ${chalk.cyan('Model')} [${defaults.defaultModel}]: `
  );
  return answer.trim() || defaults.defaultModel;
}

async function configureBaseUrl(rl, provider) {
  const defaults = providerDefaults(provider);
  if (!defaults) return '';

  const answer = await askQuestion(
    rl,
    `  ${chalk.cyan('Base URL')} [${defaults.baseUrl}]: `
  );
  return answer.trim() || defaults.baseUrl;
}

// ── Write config ───────────────────────────────────────────────────────

function writeConfig(provider, apiKey, model, baseUrl) {
  const configDir = pulseDir();
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }

  const lines = [
    '# Pulse CLI Configuration',
    '# Generated by `pulse configure`',
    `# ${new Date().toISOString()}`,
    '',
    `PROVIDER=${provider}`,
    `API_KEY=${apiKey}`,
    `MODEL=${model}`,
    `BASE_URL=${baseUrl}`,
    '',
  ];

  fs.writeFileSync(envPath(), lines.join('\n'), 'utf-8');
}

// ── Main ───────────────────────────────────────────────────────────────

/**
 * `pulse configure` — run the interactive setup wizard.
 */
async function configureCommand() {
  console.log(chalk.bold('\n  ── Pulse CLI Setup ──\n'));
  console.log(chalk.dim('  This wizard will configure your AI provider.\n'));
  console.log(chalk.dim('  Press Ctrl+C at any time to cancel.\n'));

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: true,
  });

  try {
    const provider = await selectProvider(rl);
    const apiKey = await enterApiKey(rl, provider);
    const model = await configureModel(rl, provider);
    const baseUrl = await configureBaseUrl(rl, provider);

    writeConfig(provider, apiKey, model, baseUrl);

    console.log(chalk.green(`\n  ✓ Configuration saved to ${chalk.bold(envPath())}\n`));
    console.log(chalk.dim('  You can now run `pulse` to start chatting.\n'));
  } catch (err) {
    if (err.message && err.message.includes('cancel')) {
      console.log(chalk.dim('\n  Setup cancelled.\n'));
    } else {
      throw err;
    }
  } finally {
    rl.close();
  }
}

/**
 * `pulse login` — quick API key setup for the current provider.
 * If no config exists yet, falls through to the full configure wizard.
 */
async function loginCommand() {
  // Check if partial config exists
  const envExists = fs.existsSync(envPath());
  let currentProvider = 'openai';

  if (envExists) {
    try {
      const envContent = fs.readFileSync(envPath(), 'utf-8');
      const match = envContent.match(/^PROVIDER=(.+)$/m);
      if (match) currentProvider = match[1].trim();
    } catch { /* ignore */ }
  }

  console.log(chalk.bold('\n  ── Pulse CLI Login ──\n'));

  if (envExists) {
    console.log(chalk.dim(`  Existing config found for ${chalk.bold(currentProvider)}.\n`));
  }

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: true,
  });

  try {
    const apiKey = await enterApiKey(rl, currentProvider);
    if (apiKey) {
      // Read existing config, update API key
      let existing = '';
      if (envExists) {
        existing = fs.readFileSync(envPath(), 'utf-8');
      }
      if (existing.includes('API_KEY=')) {
        existing = existing.replace(/^API_KEY=.*$/m, `API_KEY=${apiKey}`);
      } else {
        existing += `\nAPI_KEY=${apiKey}\n`;
      }
      fs.writeFileSync(envPath(), existing, 'utf-8');
      console.log(chalk.green(`\n  ✓ API key saved.\n`));
    } else {
      console.log(chalk.dim('\n  No key entered. Run `pulse configure` for full setup.\n'));
    }
  } finally {
    rl.close();
  }
}

module.exports = { configureCommand, loginCommand };
